# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aai < Formula
  desc "Copilot but for the command line"
  homepage "https://github.com/TomaszDomagala/ask-ai-cli"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TomaszDomagala/ask-ai-cli/releases/download/v0.1.5/ask-ai-cli_0.1.5_Darwin_x86_64.tar.gz"
      sha256 "503ca1fd9b8097f52ce546efe90c8ea2f323f57e4930abb37f0cc73f393a1a22"

      def install
        bin.install "aai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TomaszDomagala/ask-ai-cli/releases/download/v0.1.5/ask-ai-cli_0.1.5_Darwin_arm64.tar.gz"
      sha256 "5673d9fba502e918b01d85144abf1d58f9f736fe561638042d9b2454e822dbb5"

      def install
        bin.install "aai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomaszDomagala/ask-ai-cli/releases/download/v0.1.5/ask-ai-cli_0.1.5_Linux_arm64.tar.gz"
      sha256 "f36715b417a81b400914e3f746a4c1f3ac25aa58ef275846455040a8a85e2387"

      def install
        bin.install "aai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TomaszDomagala/ask-ai-cli/releases/download/v0.1.5/ask-ai-cli_0.1.5_Linux_x86_64.tar.gz"
      sha256 "21e255dc31f5ba9ff45005c44a49f6e4cb3dd6e39d321dc18e4610a31ae6f4d6"

      def install
        bin.install "aai"
      end
    end
  end
end
